// pokedex/src/pages/home/header/header.jsx
import React from "react";
import styles from "./header.module.scss"

export const Header = ({sortedById, changeSort}) => {

    const getSort = () => sortedById ? "#" : "AZ"

    return (<div id={styles.header}>
            <img src="/icons/Pokeball.png"/>
            <h1>Pokédex</h1>
            <span id={styles.sort} onClick={() => changeSort(!sortedById)}>
                <span>{getSort()}</span>
                <img src="/icons/Arrow.svg"/>
            </span>
        </div>)


}

// pokedex-angular/src/app/home/header/header.component.ts
import { Component, Input, OnInit } from '@angular/core';
import { BehaviorSubject } from 'rxjs';
import { AuxServiceService } from 'src/app/aux-service.service';

@Component({
  selector: 'app-header',
  templateUrl: './header.component.html',
  styleUrls: ['./header.component.scss']
})
export class HeaderComponent implements OnInit {

  sortedById: boolean = false
  
  constructor(private aux: AuxServiceService) {
    aux.sortedById.subscribe(sortedById=>{
      this.sortedById = sortedById
    })
   }

  ngOnInit(): void {

  }

  getSort(): String {
    return this.sortedById ? "#" : "AZ"
  }

  changeSort(){
    this.aux.sortedById.next(!this.sortedById)
  }

}

<div id="header">
    <img src="../../../assets/Iconos e imagenes/Pokeball.png" />
    <h1>Pokédex</h1>
    <span id="sort" (click)="changeSort()">
        <span>{{getSort()}}</span>
        <img src="../../../assets/icons/Arrow.svg" />
    </span>
</div>
