// pokedex/src/pages/home/home.jsx
import React, { useEffect, useState } from "react";
import { Link } from "react-router-dom";
import { adaptToDomain, capitalizeFirstLetter, getNumber } from "../../services/auxiliar";
import { Header } from "./header/header";
import styles from "./home.module.scss"

export const Home = ({list}) =>{

    const [sortedById, setSortedById] = useState(false)
    const [result,setResult] = useState([])

    const filter = (e) => setResult(list.filter((pokemon)=> pokemon.name.toLowerCase().includes(e.target.value.toLowerCase())))

    const applySort = (a,b) => sortedById ? a.number - b.number : a.name.localeCompare(b.name)

    useEffect(()=>{
        setResult(list)
    },[list])

    return (
        <div id={styles.wrapper}>
            <Header sortedById={sortedById} changeSort={setSortedById} />
            <input type="text"  onKeyUp={filter} placeholder="Buscar"/>
            <div id={styles.list}>
                {
                    result.sort(applySort).map(pokemon => {
                        return (
                            <Link key={pokemon.number} 
                                to={`/${pokemon.number}`} 
                                className={`${styles.pokemon} ${pokemon.types[0].toLowerCase()}`}>
                                <span className="color">
                                    <span >
                                        #{getNumber(pokemon.number)}
                                    </span>
                                    <img src={pokemon.img} />
                                </span>
                                <div>
                                    {capitalizeFirstLetter(pokemon.name)}
                                </div>
                            </Link>
                        )
                    })
                }
            </div>
        </div>
    )
}

// pokedex-angular/src/app/home/home.component.ts
import { Component, OnChanges, OnInit, SimpleChanges } from '@angular/core';
import { BehaviorSubject } from 'rxjs';
import { ApiService } from '../api.service';
import { AuxServiceService } from '../aux-service.service';

@Component({
  selector: 'app-home',
  templateUrl: './home.component.html',
  styleUrls: ['./home.component.scss']
})
export class HomeComponent implements OnInit {
  search: String = ""

  list: any[] = [ ]
  result: any[] =[]

  constructor(private api: ApiService, 
    public auxService: AuxServiceService) { }


  filter(){
    this.result = this.list.filter((pokemon)=> pokemon.name.toLowerCase().includes(this.search.toLowerCase()))
  }

  ngOnInit(): void {
    this.api.list.subscribe(list =>{
      this.list = list;
      this.auxService.sortedById.next(true)
    })
    this.list = this.api.list.getValue()
    this.auxService.sortedById.subscribe(orderById =>{
    if(orderById){
      this.result = this.list.sort((a:any,b:any) => a.number - b.number)
    }else{
      this.result = this.list.sort((a:any,b:any) => a.name.localeCompare(b.name))
    }
  })
  
  }

}

<div id="wrapper">
    <app-header ></app-header>
    <input type="text" [(ngModel)]="search" (keyup)="filter()"
    placeholder="Buscar" />
    <div id="list">
        <a *ngFor="let pokemon of result"
            [routerLink]="pokemon.number" 
            [ngClass]="'pokemon ' + pokemon.type[0].toLowerCase()" >
            <span>
                #{{auxService.getNumber(pokemon.number)}}
            </span>
            <img src="{{pokemon.img}}" />
            <div>
                {{auxService.capitalizeFirstLetter(pokemon.name)}}
            </div>
        </a>
    </div>
</div>
