// pokedex/src/pages/detail/statValues/statValue.jsx
import React from "react";
import {getNumber} from "../../../services/auxiliar";
import styles from "./statValue.module.scss"

export const StatValue = ({stat, pokemonType}) => {

    const getPercentage = (stat) => (stat * 0.5) + '%'

    return (<div className={styles.progress}>
            <span className={styles.stat}>
                {getNumber(stat)}
            </span>
            <div className={`progress-bar  ${pokemonType}`}>
                <span className="color" style={{width: getPercentage(stat)}}></span>
            </div>
        </div>)
}

// pokedex-angular/src/app/pokemon/stat-value/stat-value.component.ts
import {Component, Input, OnInit} from '@angular/core';
import {AuxServiceService} from "../../aux-service.service";

@Component({
  selector: 'app-stat-value',
  templateUrl: './stat-value.component.html',
  styleUrls: ['./stat-value.component.scss']
})
export class StatValueComponent implements OnInit {

  @Input() pokemonType: String = "";

  @Input() stat:number = 0;

  constructor(public auxService: AuxServiceService) {
  }

  ngOnInit(): void {
  }

  getPercentage(stat:number){
    return (stat*0.5)+'%'
  }

}

<span>
  {{auxService.getNumber(stat)}}
</span>
<div [ngClass]="'progress-bar ' + pokemonType">
  <span class="color" [style]="{'width':getPercentage(stat) }"></span>
</div>
