// pokedex/src/pages/detail/title/title.jsx
import React from "react";
import { Link } from "react-router-dom";
import { capitalizeFirstLetter, getNumber } from "../../../services/auxiliar";
import styles  from "./title.module.scss";

export const Title = ({pokemon}) =>{
    return (
        <div className={styles.title}>
            <Link to="/">
                <img src="/icons/arrow-left.svg" />
            </Link>
            <h1>
                {capitalizeFirstLetter(pokemon.name)}
            </h1>
            <span>
                #{getNumber(pokemon.number)}
            </span>
        </div>
    )
}

// pokedex-angular/src/app/pokemon/title/title.component.ts
import {Component, Input, OnInit} from '@angular/core';
import {AuxServiceService} from "../../aux-service.service";

@Component({
    selector: 'app-title',
    templateUrl: './title.component.html',
    styleUrls: ['./title.component.scss']
})
export class TitleComponent implements OnInit {

    @Input() pokemon: any;

    constructor(public auxService: AuxServiceService) {
    }

    ngOnInit(): void {
    }

}

<header>
  <a routerLink="/">
    <img src="../../assets/icons/arrow-left.svg">
  </a>
  <h1>
    {{auxService.capitalizeFirstLetter(pokemon.name)}}
  </h1>
  <span>
    #{{auxService.getNumber(pokemon.number)}}
  </span>
</header>
